### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by madc** [bgrsquared/d3-react-squared-c3-loader#1]
I'm getting the following `window is not defined`, when tying to implement this loader.

```
  ReferenceError: window is not defined
      at Object.<anonymous> (/Development/Web/my-app/node_modules/c3/c3.js:7303:4)
      at Module._compile (module.js:413:34)
      at Module._extensions..js (module.js:422:10)
      at Object.require.extensions.(anonymous function) [as .js] (/Development/Web/my-app/node_modules/babel-core/lib/api/register/node.js:214:7)
      at Module.load (module.js:357:32)
      at Function.Module._load (module.js:314:12)
      at Module.require (module.js:367:17)
      at require (internal/module.js:16:19)
      at r.(anonymous function).exports (/Development/Web/my-app/node_modules/d3-react-squared-c3-loader/dist/d3-react-squared-c3-loader.js:2:100)
      at Object.<anonymous> (/Development/Web/my-app/node_modules/d3-react-squared-c3-loader/dist/d3-react-squared-c3-loader.js:2:323)
      at Module._compile (module.js:413:34)
      at Module._extensions..js (module.js:422:10)
      at Object.require.extensions.(anonymous function) [as .js] (/Development/Web/my-app/node_modules/babel-core/lib/api/register/node.js:214:7)
      at Module.load (module.js:357:32)
      at Function.Module._load (module.js:314:12)
      at Module.require (module.js:367:17)
```

Installed deps: `"c3": "^0.4.11-rc4"`, `"d3-react-squared": "^0.3.6"` and `"d3-react-squared-c3-loader": "0.0.2"`.

Any ideas on what i could try?

**Comment by chroth7** [comment]
To be honest, I didn't see that error before.
What I did now: 
I adjusted some dependencies and released 0.0.3, can you try using that version?
(there is also an example added in the repo, you can try to run that (clone repo, npm install, npm run dev))

If it still doesn't work, let me know; sorry for hassle and thanks for feedback

**Comment by madc** [comment]
Thanks for your reply!
The example runs fine, but I still get the same error, when trying to implement it into my project.
I'm basically working of [this template](https://github.com/iam4x/isomorphic-flux-boilerplate) and have more or less copied your example.

Anything else, i could have a look at? I tried to mimic your webpack config, but maybe i've overlooked something.

**Comment by madc** [comment]
This could be related: https://groups.google.com/forum/#!topic/c3js/csEJ1hdZmy4

**Comment by chroth7** [comment]
oh, very good point!
I just checked on c3 source, and there is e.g. this issue: https://github.com/masayuki0812/c3/issues/1074

So that is very likely the explanation (I cannot try it here at the moment).

Also, to be honest, I never tried running d3-react-squared server side, so far I haven't written any universal apps. Did you try that? 
Or do you need c3.js?

**Comment by madc** [comment]
Ok, i just realised, that your example is rendered client-side. Guess there is nothing more to to, until c3 is updated.

Thanks for your help.

**Comment by madc** [comment]
Just as a quick info, I worked around server-side rendering with something, similar to [the suggestion here](https://github.com/kirjs/react-highcharts/issues/12#issuecomment-122085876).

```
        let graph;
        if (window === undefined) {
            graph = <div></div>;
        } else {
            const ChartC3Loader = require('d3-react-squared-c3-loader');
            graph = (<Chart c3obj={c3obj2} Loader={ChartC3Loader}/>);
        }
```
